### ISSUE TITLE
dartelmni_6_hires.nii.gz missing

### ISSUE THREAD

**Issue by plettigp** [andreashorn/lead_dbs#26]
*** Segmentation of preoperative MRI done.
Error using checkfilename>validateFilename (line 165)
Function GUNZIP was unable to find file ''/home/philip/_git/lead_dbs/templates/dartel/create_mni_darteltemplate/dartelmni_6_hires.nii.gz''.

Error in checkfilename (line 49)
[fullfilename, fid] = validateFilename( ...

Error in gunzip>checkFilesURLInput (line 118)
  [fullFileName, url] = checkfilename(inputFiles{1}, validExtensions, fcnName, ...

Error in gunzip (line 61)
[files, url, urlFilename] = checkFilesURLInput(files, {'gz'},'FILES',mfilename);

Error in ea_create_mni_darteltemplate (line 5)
gunzip([wd,'dartelmni_6_hires.nii.gz']);

Error in ea_normalize_spmdartel (line 105)
ea_create_mni_darteltemplate([options.root,filesep,options.patientname,filesep,'rc1',options.prefs.prenii_unnormalized]);

Error in ea_autocoord (line 84)
   eval([options.normalize.method,'(options)']); % triggers the normalization function and passes the options struct to it.

Error in lead>run_button_Callback (line 306)
           ea_autocoord(options);

Error in gui_mainfcn (line 95)
       feval(varargin{:});

Error in lead (line 42)
   gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)lead('run_button_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating uicontrol Callback

**Comment by andreashorn** [comment]
Thanks for reporting this, Philip. 
@ningfei, it seems we need to fix this for the git release?
Or @plettigp, did you pull only (into a blank repo)? This doesn't work, the data files would be lacking then.

**Comment by plettigp** [comment]
yep, that's exactly what i did(cloning into blank repo).
So the way to go is downloading it from the website =)
I think we can close this one

**Comment by ningfei** [comment]
@plettigp, yes, it's recommended to download lead-dbs from the website. If you download the git release or you clone the git repository (for dev purpose only), you will then need to download the data files from [here](http://www.lead-dbs.org/release/download.php?id=data) and extract them into lead-dbs folder.
