### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by andreashorn** [andreashorn/lead_dbs#30]
P. Deman reported the following error code:

Error when doing the update:
Error using textscan
Invalid file identifier. Use fopen to generate a valid file identifier.
Error in ea_update (line 57) dels=textscan(fopen([earoot,'
Error in lead>updatebutn_Callback (line 1466) ea_update;
Error in gui_mainfcn (line 95) feval(varargin{:});
Error in lead (line 42) gui_mainfcn(gui_State, varargin{:});
Error in @(hObject,eventdata)lead('
Error while evaluating uicontrol Callback >>

**Comment by ningfei** [comment]
Already fixed in the latest release.

**Comment by andreashorn** [comment]
Cool, thanks!
