### ISSUE TITLE
Initial contrast for CT-Electrodes often not well tweaked.

### ISSUE THREAD

**Issue by andreashorn** [andreashorn/lead_dbs#36]
Sometimes, CT electrodes are not visible at first in manual reconstruction window.

**Comment by plettigp** [comment]
works for me and looks great again

**Comment by andreashorn** [comment]
Also modified the check_coreg functions a bit yesterday.
In the ct/mr coreg function, you also see a combination of ct brain and bone window (basically by applying a simple tonemapping to the images).
Best, Andy

**Comment by andreashorn** [comment]
fixed
