### ISSUE TITLE
Error while trying to review reconstruction

### ISSUE THREAD

**Issue by siobhane** [andreashorn/lead_dbs#43]
I tried to review the reconstruction but after hitting the run button this error showed up: (Subject G, folder Dystonia)

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)lead('run_button_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback

**Comment by andreashorn** [comment]
Dear Siobhán, thanks for reporting! However, this error states that the subject hasnt been processed yet. You need to run reconstruction here, first.

**Comment by siobhane** [comment]
Great, thanks!
